name: Check and Upsert Fire Alerts

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check-fire-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          FIRE_API_KEY: ${{ secrets.FIRE_API_KEY }}
          MAILER_API_KEY: ${{ secrets.MAILER_API_KEY }}

        run: |
          npm run upsert-fire-alerts || true
        continue-on-error: true

      - name: Notify users
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          MAILER_API_KEY: ${{ secrets.MAILER_API_KEY }}
        run: |
          npm run notify-fire-users

      - name: Notify workflows
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: |
          npm run notify-fire-webhooks
